In [3]:
#import packages
import pandas as pd

In [3]:
#Previously I have chang
clip=pd.read_csv('/Users/sezin/PycharmProjects/AWT/data/clip.csv')
clip.head()

,Unnamed: 0,id,filename,format_long_name,duration,size,bitrate_total,video_codec,video_profile,width,height,sample_aspect_ratio,display_aspect_ratio,bitrate_video,frame_rate,created_at,updated_at
0,0,5,/Volumes/pte/content/upload/watchfolder/touchd...,QuickTime / MOV,19,41249088,17350686,h264,High 4:2:2,1920,1080,1:1,16:9,17347363,30000/1001,2019-04-05 14:00:26,2019-04-05 14:00:26
1,1,6,/Volumes/pte/content/upload/watchfolder/aspen_...,QuickTime / MOV,19,378608416,159254815,h264,High 4:2:2,1920,1080,1:1,16:9,159250292,30000/1001,2019-04-05 14:01:53,2019-04-05 14:01:53
2,2,7,/Volumes/pte/content/upload/watchfolder/freeri...,QuickTime / MOV,182,281454443,12370128,h264,High 4:4:4 Predictive,1920,1080,1:1,16:9,12292351,50/1,2019-04-05 14:03:19,2019-04-05 14:03:19
3,3,8,/Volumes/pte/content/upload/watchfolder/contro...,QuickTime / MOV,19,280986702,118191998,h264,High 4:2:2,1920,1080,1:1,16:9,118187028,30000/1001,2019-04-05 14:03:48,2019-04-05 14:03:48
4,4,9,/Volumes/pte/content/upload/watchfolder/aspen_...,QuickTime / MOV,19,231039918,97182782,h264,High 4:2:2,1920,1080,1:1,16:9,97178756,30000/1001,2019-04-05 14:03:59,2019-04-05 14:03:59

In [4]:
encode=pd.read_csv('/Users/sezin/PycharmProjects/AWT/data/encode.csv')
encode.head()

,Unnamed: 0,id,width,height,video_codec,crf,psnr,vmaf,gop_size,b_frame_interval,reference_frames,frame_rate,filename,state,stage_percentage,bitrate_video,preset,created_at,updated_at,clip_id
0,0,7,1920,1080,libx264,18,44.621550,99.406406,NaN,NaN,NaN,NaN,/Volumes/pte/content/encoding/5-1920-1080-18-7...,completed,NaN,18667784,watchfolder,2019-04-05 14:00:26,2019-04-05 14:13:47,5
1,1,8,1920,1080,libx264,19,44.051502,99.192502,NaN,NaN,NaN,NaN,/Volumes/pte/content/encoding/5-1920-1080-19-8...,completed,NaN,16379868,watchfolder,2019-04-05 14:00:26,2019-04-05 14:12:28,5
2,2,9,1920,1080,libx264,20,43.408926,98.924590,NaN,NaN,NaN,NaN,/Volumes/pte/content/encoding/5-1920-1080-20-9...,completed,NaN,14293883,watchfolder,2019-04-05 14:00:26,2019-04-05 14:11:00,5
3,3,10,1920,1080,libx264,27,38.802828,89.462670,NaN,NaN,NaN,NaN,/Volumes/pte/content/encoding/5-1920-1080-27-1...,completed,NaN,3985062,watchfolder,2019-04-05 14:00:26,2019-04-05 14:15:21,5
4,4,11,1920,1080,libx264,29,37.790129,84.728349,NaN,NaN,NaN,NaN,/Volumes/pte/content/encoding/5-1920-1080-29-1...,completed,NaN,2969404,watchfolder,2019-04-05 14:00:26,2019-04-05 14:16:54,5

In [6]:
label=pd.read_csv('/Users/sezin/PycharmProjects/AWT/data/label.csv')
label.head()

,Unnamed: 0,id,probability,time,image_number,value,classifier,created_at,updated_at,clip_id
0,0,1,90.181071,NaN,1,"punching bag, punch bag, punching ball, punchball",image_classifier_mobilenet,2019-04-08 07:23:42,2019-04-08 07:23:42,NaN
1,1,2,66.776872,NaN,2,"punching bag, punch bag, punching ball, punchball",image_classifier_mobilenet,2019-04-08 07:23:42,2019-04-08 07:23:42,NaN
2,2,3,94.055784,NaN,4,"punching bag, punch bag, punching ball, punchball",image_classifier_mobilenet,2019-04-08 07:23:42,2019-04-08 07:23:42,NaN
3,3,4,90.004504,NaN,5,"punching bag, punch bag, punching ball, punchball",image_classifier_mobilenet,2019-04-08 07:23:42,2019-04-08 07:23:42,NaN
4,4,5,95.129001,NaN,6,"punching bag, punch bag, punching ball, punchball",image_classifier_mobilenet,2019-04-08 07:23:42,2019-04-08 07:23:42,NaN

In [7]:
scene_change=pd.read_csv('/Users/sezin/PycharmProjects/AWT/data/scene_change.csv')
scene_change.head()

,Unnamed: 0,id,percentage,pts,pts_time,pos,created_at,updated_at,clip_id
0,0,1,0.2,NaN,2.34,NaN,2019-04-08 09:09:32,2019-04-08 09:09:32,7.0
1,1,2,0.2,NaN,4.68,NaN,2019-04-08 09:09:32,2019-04-08 09:09:32,7.0
2,2,3,0.2,NaN,7.14,NaN,2019-04-08 09:09:32,2019-04-08 09:09:32,7.0
3,3,4,0.2,NaN,9.74,NaN,2019-04-08 09:09:32,2019-04-08 09:09:32,7.0
4,4,5,0.2,NaN,11.42,NaN,2019-04-08 09:09:32,2019-04-08 09:09:32,7.0